site_name: Python User Group Graz
site_url: https://pygraz.org
site_author: "Python user group Graz"
site_description: "The homepage of the Python community in Graz, Austria"

repo_url: https://github.com/pygraz/ghp-website

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: black
      accent: cyan
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: cyan
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: black
      accent: cyan
  features:
    - navigation.footer
  icon:
    logo: material/snake

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

nav:
  - Overview: index.md
  - "Types of meetings": "meeting_types.md"
  - "Propose a session": "session_proposal.md"
  - "Archive": "meetings/index.md"
  - "Media":
      - "Python: The documentary": "media.md"
  - "Imprint": "imprint.md"

validation:
  nav:
    omitted_files: ignore
